<h1 align="center">
Tarea computacional # 01. (Sobre paper 1905.13729)
</h1> 

<h2 align="center">
Valentina Franco Velásquez
</h2>

<h3 align="center">
FCEN, Instituto de Física, Universidad de Antioquia
</h3>

<p align="center">
Computación Avanzada
</p>

In [23]:
#@title <font color = 'green'>Librerías</font>

import numpy as np
from itertools import product
from math import gcd
from ipywidgets import interact

In [24]:
#@title <font color = 'green'>Valor a ingresar por el usuario</font>

print('\nIngrese el valor de n (Entero >= 5):\n')

num = input()

n = int(num)

if (n%2) == 0.:
  m = int(n/2 - 1)
  print('\nn = %i y m = %i'%(n,m))

else: 
  m = int((n-3)/2)
  print('\nn = %i y m = %i'%(n,m))


Ingrese el valor de n (Entero >= 5):

6

n = 6 y m = 2


In [25]:
#@title <font color = 'green'>Código</font>

def ope(x,y):
  return (x*pow(y,2)).sum()*x - (pow(x,2)*y).sum()*y

def merge(n):

  if (n % 2) == 0.:

    m_par = int(n/2. - 1.)

    arr = list(product(range(-3,4), repeat = 2*m_par))

    final_merge = []
    final_kl = []

    for i in range(len(arr)):
      split = np.array_split(arr[i],2)

      k = split[0]
      l = split[1] 
      
      v_p = [l[0]]+[k[i] for i in range(m_par)]+[-l[0]]+[-k[i] for i in range(m_par)]
      v_m = [0,0]+[l[i] for i in range(m_par)]+[-l[i] for i in range(m_par)]

      v_pa = np.array(v_p)
      v_ma = np.array(v_m)

      merge = ope(v_pa,v_ma)

      if merge.sum() == 0 and (pow(merge,3)).sum() == 0:

        merge_pa = np.array([i for i in merge if i>=0])
        merge_na = np.array([i for i in merge if i<0])

        comp = np.isin(merge_pa,np.absolute(merge_na))

        if comp.any() == False:

          mcd = np.gcd.reduce(merge)

          if mcd !=0:
            
            simp = merge/mcd
            aux =[]

            for j in simp:
              if j<-30. or j>30. or j == 0.:
                aux.append(False)
              else:
                aux.append(True)

            auxp = np.array(aux)

            if auxp.all() == True:
              final_merge.append(simp)
              final_kl.append(arr[i])
    
    s = np.sort(final_merge)
    uni = np.unique(s,axis=0, return_index=True)
    
    def_merge = uni[0]
    def_kl = [final_kl[i] for i in uni[1]]

    return def_merge, np.array(def_kl)

  else:

    m_impar = int((n-3.)/2.)

    arr = list(product(range(-3,4), repeat = 2*m_impar+1))

    final_merge = []
    final_kl = []

    for i in range(len(arr)):
      split = np.array_split(arr[i],2)

      k = split[0]
      l = split[1] 
      
      u_p = [0]+[i for i in k]+[-i for i in k]
      u_m = [i for i in l]+[k[0],0]+[-i for i in l]+[-k[0]]

      u_pa = np.array(u_p)
      u_ma = np.array(u_m)

      merge = ope(u_pa,u_ma)

      if merge.sum() == 0 and (pow(merge,3)).sum() == 0:

        merge_pa = np.array([i for i in merge if i>=0])
        merge_na = np.array([i for i in merge if i<0])

        comp = np.isin(merge_pa,np.absolute(merge_na))

        if comp.any() == False:

          mcd = np.gcd.reduce(merge)

          if mcd !=0:

            simp = merge/mcd
            aux =[]

            for j in simp:
              if j<-30. or j>30. or j == 0.:
                aux.append(False)
              else:
                aux.append(True)

            auxp = np.array(aux)

            if auxp.all() == True:
              final_merge.append(simp)
              final_kl.append(arr[i])

    s = np.sort(final_merge)
    uni = np.unique(s,axis=0, return_index=True)
    
    def_merge = uni[0]
    def_kl = [final_kl[i] for i in uni[1]]

    return def_merge, np.array(def_kl)

In [26]:
#@title <font color = 'green'>Resultado</font>

if (n%2) == 0:

  print('\nEl conjunto de soluciones quirales (No triviales) para n = %i con valores en el rango [-30,30] y \nlos correspondientes conjuntos de (k1,...,km, l1,...,lm), con m = %i, son respectivamente: \n'%(n,m))

  join = "\n".join("{} {}".format(x, y) for x, y in zip(merge(n)[0], merge(n)[1]))
  print(join)
  print('\nCon un total de %i soluciones encontradas\n'%(len(merge(n)[0])))

else:
  print('\nEl conjunto de soluciones quirales (No triviales) para n = %i con valores en el rango [-30,30] y \nlos correspondientes conjuntos de (k1,...,km+1, l1,...,lm), con m = %i, son respectivamente: \n'%(n,m))

  join = "\n".join("{} {}".format(x, y) for x, y in zip(merge(n)[0], merge(n)[1]))
  print(join)
  print('\nCon un total de %i soluciones encontradas\n'%(len(merge(n)[0])))



El conjunto de soluciones quirales (No triviales) para n = 6 con valores en el rango [-30,30] y 
los correspondientes conjuntos de (k1,...,km, l1,...,lm), con m = 2, son respectivamente: 

[-26. -26. -16.  19.  20.  29.] [-2  1 -2 -1]
[-25.  -7.  -5.  -3.  19.  21.] [-3  1  1 -3]
[-24. -21. -11.  14.  16.  26.] [-3  2  2 -1]
[-24.  -8.  -3.  -1.  13.  23.] [-3  2 -1 -2]
[-23. -19.  -1.   3.  15.  25.] [-1  1  3 -2]
[-23. -13. -13.  10.  17.  22.] [-1 -2 -1 -3]
[-23. -12.  -7.   4.  17.  21.] [-1  2  3 -2]
[-23.  -7.  -5.  -1.  15.  21.] [-3  3  1 -2]
[-22. -17.  -2.   3.  15.  23.] [-3 -1  2  3]
[-22. -11. -10.   7.  15.  21.] [-2  0 -1  3]
[-22. -11.  -3.   1.  14.  21.] [-2  0 -1 -3]
[-22. -10.  -5.   1.  17.  19.] [-2 -3 -1  2]
[-22.  -6.  -4.  -3.  16.  19.] [-2 -3 -1  1]
[-21. -21.  -9.  11.  16.  24.] [-3 -2 -3  1]
[-21. -21.   1.   6.   9.  26.] [-3 -2 -3 -1]
[-21. -15.  -7.  10.  11.  22.] [-3 -2 -1  3]
[-21. -14.  -1.   3.  11.  22.] [-3 -1 -2  3]
[-21.  -6.  -5.  -1.  14.  1